FROM redis:5.0.1-alpine

LABEL version="0.0.1"

RUN apk --no-cache add drill

COPY entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh

WORKDIR /redis

EXPOSE 26379

ENTRYPOINT ["entrypoint.sh"]